### ISSUE TITLE
Improve our analytics/tracking system

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#337]
In order to see conversion and impressions due to our SEO changes (#333) and also to track regressions, we should have a robust system for tracking perf data points and user behaviour.

* [x] GA
  * [x] View of each route
  * [x] Usage of SearchForm (change type, change source)
  * [x] Usage of Options (Display, Font, Larivaar, LarivaarAssist)
  * ...
* [ ] Data points
  * [x] Error tracking
  * [ ] Server response time
  * [ ] Client route rendering time

**Comment by lbk003** [comment]
Any recommendations for which service to use for tracking?

**Comment by ManjotS** [comment]
Google Analytics will be used. We can provide the code via slack

**Comment by saintsoldierx** [comment]
@ManjotS is this still needed?

**Comment by ManjotS** [comment]
it looks like there are still 3 checkboxes on divjots plan that aren't yet completed.

**Comment by gurjit03** [comment]
We already have implemented google analytics.
